allow only ffv.gpg for ffv apt repository
FreifunkVogtland/ansible-config pull request #3
Opened 2021-03-11 21:40 UTC by txt-file

Signed-off-by: Vieno Hakkerinen <vieno@chemnitz.freifunk.net>

2021-03-12 06:00 UTC, ecsv commented
If you want to use Signed-By then please make sure that ffv.gpg is not in /etc/apt/trusted.gpg.d/ but in something like /etc/apt/keyrings/, /usr/share/keyrings or /usr/local/share/keyrings - otherwise ffv.gpg is still valid for all other repositories.

A month ago, there was a nice post about this on planet.debian.org: https://michael-prokop.at/blog/2021/02/16/how-to-properly-use-3rd-party-debian-repository-signing-keys-with-apt/

2021-03-12 16:34 UTC, ecsv requested changes
See the example from https://vogtland.freifunk.net/apt/README

2021-03-12 16:34 UTC, ecsv commented on roles/common/files/etc/apt/sources.list.d/ffv.list
> +deb [arch=amd64,Signed-By=/etc/apt/trusted.gpg.d/ffv.gpg] https://vogtland.freifunk.net/apt/ buster main contrib non-free
* it has to be signed-by
* comma has to be a space
* the ffv.gpg should be moved outside of /etc/apt/trusted.gpg.d

2021-03-12 17:53 UTC, ecsv commented
You can find the change I want to see in this PR in https://github.com/FreifunkVogtland/ansible-config/commit/apt-trusted-local

2021-03-18 09:42 UTC, txt-file commented
https://github.com/FreifunkVogtland/ansible-config/commit/apt-trusted-local looks good to me. You already took the time to implement the requested changes so just merge https://github.com/FreifunkVogtland/ansible-config/commit/apt-trusted-local.

I learned a lot. Thanks.

2021-03-18 09:44 UTC, ecsv commented
Merged, thanks. And also thanks for "pushing" me to finally implement the keyring stuff in the correct way on the servers :)

2021-03-18 09:44 UTC, closed without merging